### ISSUE TITLE
No statsViewer.exe file

### ISSUE THREAD

**Issue by doakjs** [nahuef/statsViewer#1]
After downloading the zip, I do not have a statsViewer.exe file, nor do I see one on the git.

**Comment by nahuef** [comment]
Hi doakjs!

Are you clicking on the link [StatsViewer_v1.0.zip](https://github.com/nahuef/statsViewer/releases/download/v1.0/StatsViewer_v1.0.zip) on the [release page](https://github.com/nahuef/statsViewer/releases)?

I just checked and there are two files in that zip, a folder named "static" and the "statsViewer.exe" file.
Could you doble check that you are downloading the right zip?
Thanks!

**Comment by nahuef** [comment]
Closing the issue, feel free to open a new one if needed.
