### ISSUE TITLE
I'm working on a similer project. Need advice please :)

### ISSUE THREAD

**Issue by Namlessking** [nahuef/statsViewer#3]
So im working on a very similer project using HTML CSS JS and Node.js. But im stuck right now and i don't know how to fix an issue that im having with csv files. This is a very weird way to ask for help, but could you please send me your email to contant you ??
Thanks ^^'

**Comment by nahuef** [comment]
Hi! Would to help you with that! 
Add me on discord Malhumoradour#5542

**Comment by Namlessking** [comment]
> Hi! Would to help you with that!
> Add me on discord Malhumoradour#5542

Thank you so much. I just sent you  a friend request, im Mr.Propre#9160

**Comment by nahuef** [comment]
Solved!
