### ISSUE TITLE
No graph

### ISSUE THREAD

**Issue by bobylatruffe** [nahuef/statsViewer#6]
Hello, 

I have just followed all the instructions, but when I launch the program, the HTML file is well generated, the html file contains the names of the exercises I have done but no chart is displayed, even when I click on "show charts".

I tried with Google Chrome and Edge

![image](https://user-images.githubusercontent.com/65607768/131248744-00fa030b-5aae-4e32-82d5-a80d66f969d2.png)

**Comment by nahuef** [comment]
Hi @bobylatruffe!

Charts are not shown because you need to have more datapoints (challenges) done.

I don't remember the exact number but it might be 10 challenges done for a scenario to have the chart shown.

Let me know if you keep grinding kovaaks and it still doesnt show any charts.

**Comment by bobylatruffe** [comment]
Hmmm okey!
I'll give it a try and get back to you in a while... well some headshots ;)
